services:
  - type: web
    name: arjundas-lost-and-found-web   # <-- Make sure this name is correct
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        # IMPORTANT: PASTE YOUR ACTUAL SECRET KEY BELOW
        value: 'your-real-secret-key-goes-here'
      - key: DATABASE_URL
        fromDatabase:
          name: lost-and-found-db   # <-- Make sure this name is correct
          property: internalDatabaseUrl